#following Always be Coding tutorial for intial setup

require 'socket'

#global variables for host/port
fileObject = File.new("oauthtoken.txt")
TWITCH_OAUTH_TOKEN_STRING = File.read(fileObject)
TWITCH_HOST = "irc.twitch.tv"
TWITCH_PORT = 6667 #default IRC port

class TBot

	#everytime a twitch bot is istantiated, authenticates it
	def initialize
		@nickname = "ProgressHasBeenMade" #chatroom bot nickname
		@password = TWITCH_OAUTH_TOKEN_STRING #generated by twitch
		@channel = "soul4rent" #channel of active account
		@socket = TCPSocket.open(TWITCH_HOST, TWITCH_PORT)

		#authentication
		write_sys "PASS #{@password}"
		write_sys "NICK #{@nickname}"
		write_sys "USER #{@nickname} 0 * #{@nickname}"
		write_sys "JOIN ##{@channel}"
	end

	def write_sys(m) #various TCP commands
		@socket.puts m
	end

	def write_chat(m) #uses write_sys to write to the chat IRC
		write_sys "PRIVMSG ##{@channel} : #{m}"
	end

	#gets messages from IRC and prints them to the console
	def run
		until @socket.eof? do
			m = @socket.gets
			puts m
			write_chat "[bot] Hello There"
		end
	end

end

#in theory code should run here.
robot = TBot.new
robot.run
